version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
    groups:
      compatible-npm-minor-patches:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
      - dependency-name: '@vitejs/plugin-react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: 'http-proxy-middleware'
        update-types: ['version-update:semver-major']
      - dependency-name: '@capacitor/*'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: 'node'
        update-types: ['version-update:semver-major']
