#!/bin/bash
# App Store Screenshots Script for LifeStreak
# This script helps capture screenshots for App Store submission

echo "=================================="
echo "LifeStreak - App Store Screenshots"
echo "=================================="
echo ""
echo "iOS Screenshot Requirements:"
echo "  - iPhone 6.7\" (1290x2796) - iPhone 14 Pro Max"
echo "  - iPhone 6.5\" (1242x2688) - iPhone 11 Pro Max, XS Max"
echo "  - iPhone 5.5\" (1242x2208) - iPhone 8 Plus, 7 Plus, 6s Plus"
echo "  - iPad Pro 12.9\" (2048x2732)"
echo ""
echo "Android Screenshot Requirements:"
echo "  - Phone: 1080x1920 or 1080x2340"
echo "  - 7\" Tablet: 1200x1920"
echo "  - 10\" Tablet: 1600x2560"
echo ""
echo "=================================="
echo "Screenshot Checklist:"
echo "=================================="
echo ""
echo "📱 Recommended Screenshots to Capture:"
echo ""
echo "1. Home/Dashboard - Daily tasks and progress overview"
echo "2. Daily Text - Scripture reading with reflection"
echo "3. Bible Reading - Progress tracking view"
echo "4. News Feed - JW.org news articles"
echo "5. Statistics - Progress charts and achievements"
echo "6. Settings - Notification preferences"
echo ""
echo "=================================="
echo "How to Capture:"
echo "=================================="
echo ""
echo "iOS Simulator:"
echo "  1. Open Xcode"
echo "  2. Window → Devices and Simulators"
echo "  3. Select required device size"
echo "  4. Run app: npx cap open ios"
echo "  5. Cmd+S to save screenshot"
echo ""
echo "Android Emulator:"
echo "  1. Open Android Studio"
echo "  2. Tools → Device Manager"
echo "  3. Create device with required resolution"
echo "  4. Run app: npx cap open android"
echo "  5. Use emulator screenshot button"
echo ""
echo "Physical Device:"
echo "  iOS: Side button + Volume up"
echo "  Android: Power + Volume down"
echo ""
echo "=================================="
echo "Output Directory:"
echo "=================================="
echo ""

OUTPUT_DIR="app-store-assets/screenshots"
mkdir -p "$OUTPUT_DIR/ios"
mkdir -p "$OUTPUT_DIR/android"

echo "Created: $OUTPUT_DIR/ios/"
echo "Created: $OUTPUT_DIR/android/"
echo ""
echo "Save your screenshots to these folders."
echo ""
